service: CMS
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  profile: APIStartUp
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "dynamodb:*"
          Resource: "*"
        - Effect: Allow
          Action: "s3:*"
          Resource: "*"

functions:
  app:
    handler: src/handler.routesHandlers
    events:
      - http:
          path: /{proxy+}
          method: ANY

custom:
  bundle:
    linting: false

package:
  individually: false

plugins:
  - serverless-dotenv-plugin
  - serverless-bundle
  - serverless-offline
