service: CMS
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: APIStartUp
  region: ap-southeast-1

functions:
  user: 
    handler: src/handler.routesHandlers
    events:
      - http: 
          path: /user/{proxy+}
          method: ANY

  post: 
    handler: src/handler.routesHandlers
    events:
      - http: 
          path: /post/{proxy+}
          method: ANY

custom:
  bundle:
    linting: false


package:
  individually: false 

plugins:
  # - serverless-plugin-typescript
  - serverless-bundle